Develop2
java-park-mail-ru/PerpetuumMobile-02-2018 pull request #1
Opened 2018-02-28 16:23 UTC by PDmitryA

2018-02-28 18:20 UTC, KSolovyev commented
Не настроен travis. Надо поправить перед всеми проверками

2018-02-28 19:46 UTC, Badya requested changes
Трэвис чиним, мусор из проекта выносим

2018-02-28 19:46 UTC, Badya commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Этого тут быть не должно

2018-02-28 19:46 UTC, Badya commented on src/main/java/main/SimpleController.java
> +    public static class Message {
У вас уже есть подобный класс

2018-02-28 19:46 UTC, Badya commented on src/main/java/server/Controller/RegistrationController.java
> +public class RegistrationController {
Этот контроллер спрингом не проигнорируется?

2018-02-28 19:46 UTC, Badya commented on src/main/java/server/Messages/MessageStates.java
> +public class MessageStates {
Можно использовать enum

2018-02-28 19:46 UTC, Badya commented on src/main/java/server/Services/UserService.java
> +@Service
Эту аннотацию лучше ставить на интерфейс

2018-02-28 19:46 UTC, Badya commented on src/main/java/server/Services/UserService.java
> +        return false;
Что тут не так? (в РК есть вопрос по теории на эту тему)

2018-03-01 11:15 UTC, PDmitryA commented on src/main/java/server/Messages/MessageStates.java
> +public class MessageStates {
Нам показалось так понятней. Переделать? Почему enum лучше?

2018-03-01 11:20 UTC, PDmitryA commented on src/main/java/main/SimpleController.java
> +    public static class Message {
Это класс с лекции, только пример - для нас удобнее смотреть сюда. Наш проект в папке server. Этот класс никак не участвует в серверной части.

2018-03-01 11:45 UTC, Badya commented on src/main/java/main/SimpleController.java
> +    public static class Message {
сделайте Gist, а это удалите

2018-03-01 11:47 UTC, Badya requested changes
Трэвис все еще лежит

2018-03-01 11:47 UTC, Badya commented on src/main/java/server/Messages/MessageStates.java
> +public class MessageStates {
Это я у вас на РК спрошу почему enum лучше)

2018-03-01 14:24 UTC, InfantryMan commented
Трэвис починили, теперь работает

2018-03-12 11:49 UTC, Badya requested changes

2018-03-12 11:49 UTC, Badya commented on src/main/java/server/controller/AuthorizationController.java
> +@CrossOrigin(origins = {"http://127.0.0.1:3000", "http://localhost:3000", "https://blend-front.herokuapp.com", "https://blendocu.herokuapp.com"}, allowCredentials = "true")
Это можно вынести в конфиг/параметр

2018-03-12 11:49 UTC, Badya commented on src/main/java/server/controller/ScoreboardController.java
> +//import java.util.Comparator;
?

2018-03-12 11:49 UTC, Badya commented on src/main/java/server/messages/MessageStates.java
> +public class MessageStates {
enum

2018-03-12 11:49 UTC, Badya commented on src/main/java/server/services/FileSystemStorageService.java
> +    //private final Path rootLocation;
?

2018-03-12 11:49 UTC, Badya commented on src/main/java/server/services/FileSystemStorageService.java
> +        storageProperties = new StorageProperties("upload-dir");
инициализировать с объявлением

2018-03-12 11:49 UTC, Badya commented on src/main/java/server/services/UserService.java
> +        allUsers.put(ID_GENERATOR.getAndIncrement(), new User("her", "her@mail.ru", "her", 10));
Это надо убрать

2018-03-12 11:49 UTC, Badya commented on src/main/java/server/controller/FileUploadController.java
> +    @GetMapping("/")
?

2018-03-12 11:49 UTC, Badya commented on src/main/java/server/controller/AuthorizationController.java
> +        System.out.println("GOGO" + userImage);
logging

2018-03-12 11:49 UTC, Badya commented on src/main/java/server/controller/AuthorizationController.java
> +        if (changeEmail) {
это проверяется 3 раза - очень запутанная логика

2018-03-13 13:00 UTC, PDmitryA commented on src/main/java/server/services/UserService.java
> +        allUsers.put(ID_GENERATOR.getAndIncrement(), new User("her", "her@mail.ru", "her", 10));
Что именно, мапу юзеров? Мы пока что не создавали базу данных, впоследствии, конечно, сделаем. Но её же не надо было сдавать к 1 рк...

2018-03-18 21:03 UTC, InfantryMan commented on src/main/java/server/messages/MessageStates.java
> +public class MessageStates {
Сделано

2018-03-18 21:03 UTC, InfantryMan commented on src/main/java/server/controller/AuthorizationController.java
> +@CrossOrigin(origins = {"http://127.0.0.1:3000", "http://localhost:3000", "https://blend-front.herokuapp.com", "https://blendocu.herokuapp.com"}, allowCredentials = "true")
Сделано

2018-03-18 21:03 UTC, InfantryMan commented on src/main/java/server/controller/ScoreboardController.java
> +//import java.util.Comparator;
Сделано

2018-03-19 15:00 UTC, InfantryMan commented on src/main/java/server/controller/AuthorizationController.java
> +        if (changeEmail) {
Пока что мы решили оставить так, потому что пользователь может поменять любую комбинацию данных.

2018-03-27 18:00 UTC, Badya requested changes
Тесты уберите в РК2

2018-03-27 18:00 UTC, Badya commented on src/main/java/server/messages/MessageStates.java
> +//public class MessageStates {
?

2018-03-30 13:53 UTC, gtt142 commented on src/main/java/server/messages/MessageStates.java
> +//public class MessageStates {
Исправил

2018-04-04 19:53 UTC, merged