Game
java-park-mail-ru/PerpetuumMobile-02-2018 pull request #3
Opened 2018-05-02 10:18 UTC by gtt142

2018-05-02 16:53 UTC, KSolovyev commented
конфликты. И можно в описание ссылку на фронт?

2018-05-02 17:41 UTC, KSolovyev requested changes

2018-05-02 17:41 UTC, KSolovyev commented on src/main/java/server/WebSocketConfig.java
> +//public class WebSocketConfig implements WebSocketConfigurer {
? 😢

2018-05-02 17:41 UTC, KSolovyev commented on src/main/java/server/controller/AuthorizationController.java
>                          || changeUser.getLogin().equals(""));
есть такая штука, как `StringUtils.isEmpty`

2018-05-02 17:41 UTC, KSolovyev commented on src/main/java/server/controller/AuthorizationController.java
>          if (changeEmail && changeLogin) {
Пользователя бы за один запрос в бд обновлять

2018-05-02 17:41 UTC, KSolovyev commented on src/main/java/server/controller/GameController.java
> +public class GameController {
Не пойдет, нужно переделать на websocket'ы

2018-05-06 13:31 UTC, KSolovyev requested changes
Договорились на рк3 сделать вставку кубиков в произвольное место без проверки цветов.

2018-05-21 19:24 UTC, KSolovyev commented
Конфликты(((
Порешайте, потом буду смотреть

2018-05-27 20:22 UTC, KSolovyev requested changes

2018-05-27 20:22 UTC, KSolovyev commented on src/main/java/server/controller/GameInfoController.java
> +        }
логику с базой надо вынести либо в сервис, либо в DAO

2018-05-27 20:22 UTC, KSolovyev commented on src/main/java/server/controller/GameInfoController.java
> +        }
работу с файлами надо вынести в сервис

2018-05-27 20:22 UTC, KSolovyev commented on src/main/java/server/mechanic/MechanicsExecutor.java
> +                    //gameMechanics.reset();
уберите закомментированный код

2018-05-27 20:22 UTC, KSolovyev commented on src/main/java/server/mechanic/services/GameSessionService.java
> +            e.printStackTrace();
логирование должно быть сделано только через логгер

2018-05-27 20:22 UTC, KSolovyev commented on src/main/java/server/mechanic/services/GameSessionService.java
> +            ignored.getMessage();
в таких случаях можно немного сами настройки чеккера поправить.

2018-05-27 20:22 UTC, KSolovyev commented on src/main/java/server/services/UserService.java
> +            ex.printStackTrace();
логгирование через логгер

2018-05-27 20:22 UTC, KSolovyev commented on src/main/java/server/services/UserService.java
> +            return true;
вы вот тут возвращаете boolean, а результат нигде не используется

2018-05-27 20:22 UTC, KSolovyev commented on src/test/java/server/mechanic/GameMechanicsTest.java
> +    void gameStartedTest() {
хочется больше игровых тестов

2018-05-27 20:22 UTC, KSolovyev commented on src/main/java/server/mechanic/messages/inbox/SetCubic.java
> +            cell -> cell.getCoordX().equals(this.coordX) && cell.getCoordY().equals(this.coordY) && !cell.isFixed()
а если я пришлю сообщение, что поставил фиксированный кубик, мне засчитается очко?

2018-05-31 13:55 UTC, gtt142 commented on src/main/java/server/mechanic/messages/inbox/SetCubic.java
> +            cell -> cell.getCoordX().equals(this.coordX) && cell.getCoordY().equals(this.coordY) && !cell.isFixed()
Нет, не засчитается

2018-05-31 18:24 UTC, KSolovyev approved these changes

2018-05-31 18:26 UTC, merged