Game multithread
java-park-mail-ru/PerpetuumMobile-02-2018 pull request #4
Opened 2018-05-30 10:23 UTC by gtt142

РК №4

2018-05-30 19:29 UTC, KSolovyev commented
Поправьте предыдущий пр сначала

2018-05-30 20:15 UTC, Badya requested changes

2018-05-30 20:15 UTC, Badya commented on src/main/java/server/controller/AuthorizationController.java
> +                e.printStackTrace();
Логгирование сделайте

2018-05-30 20:15 UTC, Badya commented on src/main/java/server/controller/AuthorizationController.java
> +                mailService.sendEmail(emailNoreply, oldUser.getEmail(), "E-mail changing.", msg);
это 2 раза шлется?

2018-05-30 20:15 UTC, Badya commented on src/main/java/server/controller/AuthorizationController.java
> +        StringBuilder symbols = new StringBuilder();
Порефакторь меня =)

2018-05-30 20:15 UTC, Badya commented on src/main/java/server/controller/GameInfoController.java
> +public class GameInfoController {
Этот контроллер сошел с ума и он очень хочет чтобы у него появился сервис

2018-05-30 20:15 UTC, Badya commented on src/main/java/server/mechanic/GameMechanicsImpl.java
> +    public void gmStep(int threadCount) {
Порефакторь меня =)

2018-05-30 20:15 UTC, Badya commented on src/main/java/server/mechanic/GameMechanicsImpl.java
> +        while (!tasks.isEmpty()) {
Положим ситуацию - очередь никогда не опустеет от тасков?

2018-05-30 20:15 UTC, Badya commented on src/main/java/server/mechanic/game/GameSession.java
> +        gameSessionService.finishGame(this, getEnemy(userId).getUserId(), reasonFirst, reasonSecond);
Что-то со связностью GameSessionService вроде рулит сессиями, но сессия при этом убивает себя, между ними явно циклическая зависимость

2018-05-30 20:15 UTC, Badya commented on src/main/java/server/mechanic/services/event/client/ClientEventService.java
> +@Service
Сервисы - синглтоны

2018-05-30 20:45 UTC, gtt142 commented on src/main/java/server/controller/AuthorizationController.java
> +                mailService.sendEmail(emailNoreply, oldUser.getEmail(), "E-mail changing.", msg);
Да. На старый и новый адрес.

2018-05-30 20:45 UTC, gtt142 commented on src/main/java/server/controller/GameInfoController.java
> +public class GameInfoController {
В процессе

2018-05-31 10:45 UTC, Badya commented on src/main/java/server/controller/AuthorizationController.java
> +                mailService.sendEmail(emailNoreply, oldUser.getEmail(), "E-mail changing.", msg);
Ну пускай может почтоСервис сам это внутри реализует?

2023-07-13 14:55 UTC, closed without merging